ALTER TABLE settlements
    ADD COLUMN IF NOT EXISTS iron_amount  DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS iron_rate    DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS iron_cap     DOUBLE PRECISION NOT NULL DEFAULT 500,
    ADD COLUMN IF NOT EXISTS iron_calc_at TIMESTAMPTZ NOT NULL DEFAULT now();
